export const DEFAULT_LIGHT_THEME = {
  colors: {
    accentcolor: null,
    bookmark_text: null,
    button_background_active: null,
    button_background_hover: null,
    frame: "rgb(240, 240, 244)",
    frame_inactive: "rgb(235, 235, 239)",
    icons: "rgb(91,91,102)",
    icons_attention: null,
    ntp_background: "#F9F9FB",
    ntp_card_background: null,
    ntp_text: "rgb(21, 20, 26)",
    popup: "#fff",
    popup_border: "rgb(240,240,244)",
    popup_highlight: "#e0e0e6",
    popup_highlight_text: "#15141a",
    popup_text: "rgb(21,20,26)",
    sidebar: "rgb(255, 255, 255)",
    sidebar_border: null,
    sidebar_highlight: null,
    sidebar_highlight_text: null,
    sidebar_text: "rgb(21, 20, 26)",
    tab_background_separator: null,
    tab_background_text: "rgb(21,20,26)",
    tab_line: "transparent",
    tab_loading: null,
    tab_selected: "#fff",
    tab_text: "rgb(21,20,26)",
    textcolor: null,
    toolbar: "#f9f9fb",
    toolbar_bottom_separator: "#ccc",
    toolbar_field: "rgb(240, 240, 244)",
    toolbar_field_border: "transparent",
    toolbar_field_border_focus: null,
    toolbar_field_focus: "white",
    toolbar_field_highlight: null,
    toolbar_field_highlight_text: null,
    toolbar_field_separator: null,
    toolbar_field_text: "rgb(21, 20, 26)",
    toolbar_field_text_focus: null,
    toolbar_text: "rgb(21,20,26)",
    toolbar_top_separator: "transparent",
    toolbar_vertical_separator: null,
    popup_action_color: "rgb(91,91,102)",
    button: "rgba(207,207,216,.33)",
    button_hover: "rgba(207,207,216,.66)",
    button_active: "rgb(207,207,216)",
    button_primary: "rgb(0, 97, 224)",
    button_primary_hover: "rgb(2, 80, 187)",
    button_primary_active: "rgb(5, 62, 148)",
    button_primary_color: "rgb(251, 251, 254)",
    input_color: "rgb(21,20,26)",
    input_background: "rgb(255,255,255)",
    urlbar_popup_hover: "rgb(240,240,244)",
    urlbar_popup_separator: "rgb(240,240,244)",
    tab_icon_overlay_stroke: "rgb(255,255,255)",
    tab_icon_overlay_fill: "rgb(91,91,102)",
  },
  images: null,
  properties: {
    additional_backgrounds_alignment: null,
    additional_backgrounds_tiling: null,
    color_scheme: "light",
    content_color_scheme: null,
    panel_hover: "color-mix(in srgb, currentColor 12%, transparent)",
    panel_active: "color-mix(in srgb, currentColor 20%, transparent)",
    panel_active_darker: "color-mix(in srgb, currentColor 27%, transparent)",
    toolbar_field_icon_opacity: "0.72",
    zap_gradient:
      "linear-gradient(90deg, #9059FF 0%, #FF4AA2 52.08%, #FFBD4F 100%)",
    system: "true",
  },
};
